// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jazmygufltlqjwqrpbnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imphem15Z3VmbHRscWp3cXJwYm5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzE4NzUsImV4cCI6MjA3Mzc0Nzg3NX0.XRbNQQ96WTOUEJXJo6dNJ3NAgbWCm9U70p-PyC563Yc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});